### ISSUE TITLE
[1.19.2] Exception error in log using dark GUI button

### ISSUE THREAD

**Issue by kwpugh** [UnhappyCodings/vanillaquarry#1]
Latest version.

https://gist.github.com/kwpugh/3309d7724064e87b09518f0c35216bbc

I think you are just missing a texture.

Nice mod.

**Comment by UnhappyCodings** [comment]
Hey! 

Thanks for your issue report. 
Indeed there was a file named wrong. Cant really tell why, because it worked for me haha
However, fix has been uploaded to Curseforge in 1.18 and 1.19!

**Comment by UnhappyCodings** [comment]
Little information: The upload to curseforge could take some hours, maybe until tomorrow, due to its sunday.

**Comment by kwpugh** [comment]
Thanks.
