### ISSUE TITLE
'Rendering screen' crash connected to the quarry item in inventory

### ISSUE THREAD

**Issue by MK99MA** [UnhappyCodings/vanillaquarry#2]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

Hi,

I don't know if your mod is actually responsible for the crash, but it certainly does play a role:

I can place and use the quarry as well as the area card just fine and there are no issues with it. However if I destroy the quarry and pick it up, my game would crash as soon as I move my mouse over the quarry item in my inventory. 

The issue is easily reproducable as it occurs all the time. It also happened after I removed and readded the mod and did the same steps as before (placing & using, then collecting it) both with v1.3r and 1.4r.

As I stated above, it's not necessarily the fault of your mod, since it could just be a basic incompatibility I don't know of yet, but so far it's the only item in my setup that would cause this and so it's my only hint in investigating it.

I attached a log and a video of the crash I'm receiving if that is of any help to you. 
[crash-2022-11-01_14.26.34-client.txt](https://github.com/UnhappyCodings/vanillaquarry/files/9910300/crash-2022-11-01_14.26.34-client.txt)

https://user-images.githubusercontent.com/44809419/199250101-84d61f3d-1c68-4168-9104-0ec492946918.mp4

### Multiplayer?

Multiplayer

### Operating System?

Windows

### Version

Other

### Minecraft Version

1.18.2

### Forge Version

40.1.80

**Comment by UnhappyCodings** [comment]
Hey! Thanks for reporting this to me, I already ran into a problem like this.
Could you please try the dev release I am appending to this post?
Is it still crashing? **Dont forget to unzip the file!**
[quarry-1.18.2-1.5r.zip](https://github.com/UnhappyCodings/vanillaquarry/files/9913347/quarry-1.18.2-1.5r.zip)

**Comment by UnhappyCodings** [comment]
The above reported issue will be fixed and uploaded to Curseforge soon!
If you have any other questions related to this post, feel free to post them.
Otherwise you can close the issue now.

If you have any other question feel free to join our discord server: https://discord.intelligence-modding.de/
Thank you for the report and have a nice day! :)
