### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: Index 99 out of bounds for length 14

### ISSUE THREAD

**Issue by CMAE2** [UnhappyCodings/vanillaquarry#4]
[crash-2022-11-12_20.58.23-server.txt](https://github.com/UnhappyCodings/vanillaquarry/files/9996360/crash-2022-11-12_20.58.23-server.txt)

No apparent external cause.

**Comment by UnhappyCodings** [comment]
Can you please provide more Informations on this case? Is it a server, lan, singleplayer. When does the error throw?

**Comment by Seniorendi** [comment]
This is the most descriptive issue report I've ever seen

**Comment by CMAE2** [comment]
It takes place in a single player world while mining with the card set to
box mode and fortune set with a speed 0f 1, I've  started with version 1.4
but it happened again with the 1.7 build. so far it just happens at random.
In one case it happened on world load, however this only happened once. My
hypothesis is it might be how the miner keeps track of the block it breaks.
I only say this because so far it only happens when it is mining, though, I
do not know if this is relevant but a create schematic intersects the mined
area but as near as I can tell it hasn't happened when a block breaks in
the schematic area.

**Comment by CMAE2** [comment]
this is the console output right before an error is thrown.

[15:41:21] [Server thread/WARN] [os.ut.pl.wi.WmiQueryHandler/]: COM
exception: Invalid Query: SELECT PERCENTUSAGE FROM
Win32_PerfRawData_PerfOS_PagingFile

**Comment by UnhappyCodings** [comment]
Hey!

the above reported issue is fixed and is already been uploaded to Curseforge!
If you have any other questions related to this post, feel free to post them.
Otherwise you can close the issue now.

If you have any other question feel free to join our discord server: https://discord.intelligence-modding.de/
Thank you for the report and have a nice day! \:)
