### ISSUE TITLE
the quarry does not mine anything

### ISSUE THREAD

**Issue by Nosnate** [UnhappyCodings/vanillaquarry#5]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I found the error that the quarry no longer breaks down, it still worked on the first try. now it only consumes the coal and does nothing else. dismantling and relocating them didn't help.

### Multiplayer?

Singleplayer

### Operating System?

Windows

### Version

Other

### Minecraft Version

1.19.2

### Forge Version

43.2.0

### Links

https://postimg.cc/gallery/3Y4ddW9

**Comment by UnhappyCodings** [comment]
Hey! Did you change one of the two positions before it stopped working?

**Comment by Nosnate** [comment]
Yes, I changed both positions. And tried several places.

**Comment by UnhappyCodings** [comment]
Hey! Sorry for taking so long to fix this. Bug has been fixed and version 1.6.5r is now available on 1.18/1.19.
https://www.curseforge.com/minecraft/mc-mods/quarry
